### ISSUE TITLE
Always merge old homeworks

### ISSUE THREAD

**Issue by migglu** [L3K0V/litebelt#12]

**Comment by L3K0V** [comment]
@migglu коментара дето тряше да мърджаваме взимайки предвид наказанието и това issue какво общо имат?

**Comment by L3K0V** [comment]
[Този коментар](https://github.com/L3K0V/litebelt/commit/bc730056b9de9b62dbb71297b876801fd3292073#commitcomment-19415731)

**Comment by migglu** [comment]
@L3K0V онова беше за това, че максималните точки ти стават по-малко, това е за това, че не би трябвало да остават отворени пул рекуести от стари домашни когато ги поправят.. То може би това включва и онзи случай в себе си

**Comment by L3K0V** [comment]
Тоест при всички случаи ако едно домашно е старо затваряме? И сега с тоз ред дето го променихме не прихващаме случаите в които не са пълни точки за старо домашно, нали?
